#!/usr/bin/env c:\xampp\php\php.exe
<?php
/**
 * You can use another configuration file
 */
//$xmlConfigFile = __DIR__ . DIRECTORY_SEPARATOR . 'commithook.xml';
$hookName = __FILE__;
$runnerPhp = realpath(__DIR__ . '/../../../commithook/LibHooks/runner.php');
require_once $runnerPhp;
