#!/usr/bin/env c:\xampp\php\php.exe
<?php
/**
 * Configure following string if you put commit hooks located not in the same dir.
 */
$hookName = __FILE__;
$runnerPhp = realpath(__DIR__ . '/../../../commithook/bin/runner.php');
require_once $runnerPhp;

