<?php
/** @var $this Mage_Core_Block_Template */
$_myVar = $this->getSomeData();
$myProtected = $this->_getProtectedData();
$label = $this->__('Test');
?>

<script type="text/javascript">
    jQuery(document).ready(function(){

    });
</script>


<div>
    <?php foreach ($this->getData('array') as $_value) { ?>
        <?php echo $_value; ?>
    <?php } ?>
    <?php if ($this->getData('aa') === 'some string') { ?>
        <?php echo $_myVar; ?>
    <?php } ?>


    <?php foreach ($this->getData('array222') as $value) : ?>
        <?php echo SomeClass::someMethod($value); ?>
    <?php endforeach; ?>


    <?php if ($this->getData('bbb') === 'some string') : ?>
        <?php echo $myProtected; ?>
        <?php echo Mage::helper($value); ?>
    <?php endif; ?>
</div>

<?php echo $this->getBlockHtml('formkey') ?>

<script type="text/javascript">
    jQuery(document).ready(function(){
        <?php echo Mage::helper($value); ?>
    });
</script>

<?php
if ($product->isSaleable() && $this->hasOptions()
        && $this->getChildChildHtml('container2')
    ):
    ?>
    <div class="product-options">
        <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
    </div>
<?php endif; ?>
<?php if ($i != $recommendationsCount-1) echo ","?>
<?php $_product = $this->getProduct(); ?>
<?php Mage::getModel('catalog/product'); ?>
