#!/usr/bin/env php
<?php

/** @var Composer\Autoload\AutoloadGenerator $autoloader */
$autoloader = require_once 'autoload.php';
$autoloader->addPsr4('PreCommit\\', array(__DIR__ . '/lib/PreCommit/'));

use Symfony\Component\Console;
use PreCommit\Install;
$install = new Install(realpath(__DIR__ . '/..'));
$install->run(
    new Console\Input\ArgvInput(),
    new Console\Output\ConsoleOutput()
);

